baseURL: "https://quadrateinfo.ru/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Квадрат Инфо"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Квадрат Инфо"
  description: "Мы специализируемся на предоставлении услуг по разработке веб-сайтов, приложений, построению и поддержке бизнеса для клиентов."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
    - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "trungkienspktnd@gamail.com"
    - "207.555.0119"

  copyright: "© 2023 ООО "Квадрат Инфо""

  postProcess: false

menus:
  main:
    - name: "Главная"
      url: "/#hero"
      weight: 1

    - name: "Как мы работаем"
      url: "/#"
      weight: 2

    - name: "Наша команда"
      url: "/#"
      weight: 3

    - name: "Цены"
      url: "/#"
      weight: 4

    - name: "Блог"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Контакты"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Главная"
      url: "/#hero"
      weight: 1

    - name: "Как мы работаем"
      url: "/#"
      weight: 2

    - name: "Наша команда"
      url: "/#"
      weight: 3

    - name: "Цены"
      url: "/#"
      weight: 4

    - name: "Блог"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
